CREATE TABLE ItemServico (
ID INTEGER PRIMARY KEY,
IDServico INTEGER,
IDProduto INTEGER
)

CREATE TABLE Produto (
ID INTEGER PRIMARY KEY,
Nome VARCHAR(50),
PrecoVenda DECIMAL(10),
Empresa VARCHAR(50),
Quantidade DECIMAL(10),
Categoria VARCHAR(50),
PrecoCompra DECIMAL(10)
)

CREATE TABLE Servico (
ID INTEGER PRIMARY KEY,
Descricao VARCHAR(50),
Preco DECIMAL(10)
)

/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DO SERVICO DENTRO DA TABELA Compra*/
CREATE TABLE Compra (
ID INTEGER PRIMARY KEY,
TipoPagamento VARCHAR(25),
ValorTotal DECIMAL(),
IDServico INTEGER,
IDCliente INTEGER,
FOREIGN KEY(IDServico) REFERENCES Servico (ID)
)

CREATE TABLE Usuario (
ID INTEGER PRIMARY KEY,
Nome VARCHAR(50),
Email VARCHAR(35),
Senha VARCHAR(15)
)

/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DA COMPRA DENTRO DA TABELA Parcela*/
CREATE TABLE Parcela (
ID INTEGER PRIMARY KEY,
Valor DECIMAL(10),
DataVencimento DATETIME,
IDCompra INTEGER,
FOREIGN KEY(IDCompra) REFERENCES Compra (ID)
)

CREATE TABLE Cliente (
ID INTEGER PRIMARY KEY,
CPF VARCHAR(10),
Nome VARCHAR(50),
Contato VARCHAR(50),
DataNascimento DATETIME,
Email VARCHAR(35)
)

/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DO CLIENTE DENTRO DA TABELA Endereco*/
CREATE TABLE Endereco (
ID INTEGER PRIMARY KEY,
CEP VARCHAR(10),
Cidade VARCHAR(25),
Estado VARCHAR(25),
Rua VARCHAR(50),
IDCliente INTEGER,
FOREIGN KEY(IDCliente) REFERENCES Cliente (ID)
)

/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DO SERVIÇO DENTRO DA TABELA ItemServico*/
ALTER TABLE ItemServico ADD FOREIGN KEY(IDServico) REFERENCES Servico (ID)
/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DO PRODUTO DENTRO DA TABELA ItemServico*/
ALTER TABLE ItemServico ADD FOREIGN KEY(IDProduto) REFERENCES Produto (ID)
/* CHAVE ESTRANGEIRA REFERENCIANDO O ID DO CLIENTE DENTRO DA TABELA Compra*/
ALTER TABLE Compra ADD FOREIGN KEY(IDCliente) REFERENCES Cliente (ID)
